#!/usr/bin/env python
import sys
import IPython

banner = 'IPython {} - Python {}\n'
python_version = sys.version.split(' ', 1)[0]
ipython_version = IPython.__version__

c = get_config()
c.TerminalInteractiveShell.separate_in = ''
c.TerminalInteractiveShell.banner1 = banner.format(ipython_version, python_version)
c.PromptManager.out_template = ''
c.PromptManager.in2_template = '... '
c.PromptManager.justify = False
c.PromptManager.in_template = '>>> '
