set -g display-time 3000
set -g pane-active-border-bg "#3a3a3a"
set -g pane-active-border-fg "#87d7ff"
set -g pane-border-bg "#3a3a3a"
set -g pane-border-fg "#3a3a3a"
set -g status-bg "#3a3a3a"
set -g status-fg "#87d7ff"
set -g history-limit 10000
setw -g window-status-current-attr bright
